// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ERPSoft.DATA.Models;

public partial class Entrada
{
    public int NotaFiscal { get; set; }

    [Required]
    [StringLength(150)]
    [Unicode(false)]
    public string NomeDeposito { get; set; }

    [Column(TypeName = "date")]
    public DateTime DataCadastro { get; set; }

    [StringLength(150)]
    [Unicode(false)]
    public string NomeFornecedor { get; set; }

    [StringLength(150)]
    [Unicode(false)]
    public string NomeProduto { get; set; }

    [Column("EntradaQTDA")]
    public int EntradaQtda { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string DataFormatada { get; set; }

    [Key]
    public int Id { get; set; }

    public int IdEntradaProduto { get; set; }

    public int IdEntradaFornecedor { get; set; }

    [ForeignKey("IdEntradaFornecedor")]
    [InverseProperty("Entrada")]
    public virtual Fornecedor IdEntradaFornecedorNavigation { get; set; }

    [ForeignKey("IdEntradaProduto")]
    [InverseProperty("Entrada")]
    public virtual Produto IdEntradaProdutoNavigation { get; set; }
}