// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ERPSoft.DATA.Models;

public partial class OrdemCompra
{
    public int CodPedidoMaterial { get; set; }

    [Column(TypeName = "date")]
    public DateTime DataCadastro { get; set; }

    [StringLength(10)]
    public string DataFormatada { get; set; }

    [Column("QTDA")]
    public int Qtda { get; set; }

    public int Valor { get; set; }

    public int Total { get; set; }

    [StringLength(10)]
    public string Ordem { get; set; }

    [StringLength(150)]
    [Unicode(false)]
    public string NomeFornecedor { get; set; }

    [Key]
    public int Id { get; set; }

    public int IdOrdemPedidoMaterial { get; set; }

    public int IdOrdemFornecedor { get; set; }

    [ForeignKey("IdOrdemFornecedor")]
    [InverseProperty("OrdemCompra")]
    public virtual Fornecedor IdOrdemFornecedorNavigation { get; set; }

    [ForeignKey("IdOrdemPedidoMaterial")]
    [InverseProperty("OrdemCompra")]
    public virtual PedidoMaterial IdOrdemPedidoMaterialNavigation { get; set; }
}