// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ERPSoft.DATA.Models;

public partial class PedidoMaterial
{
    [StringLength(150)]
    [Unicode(false)]
    public string Departamento { get; set; }

    [StringLength(150)]
    [Unicode(false)]
    public string Usuario { get; set; }

    [Column(TypeName = "date")]
    public DateTime DataCadastro { get; set; }

    [Column("EAN")]
    public int Ean { get; set; }

    [StringLength(150)]
    [Unicode(false)]
    public string NomeProduto { get; set; }

    [StringLength(10)]
    public string DataFormatada { get; set; }

    [StringLength(150)]
    [Unicode(false)]
    public string Fabricante { get; set; }

    [Required]
    [StringLength(30)]
    [Unicode(false)]
    public string StatusMaterial { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Unidade { get; set; }

    [Column("QTDA")]
    public int? Qtda { get; set; }

    public int Cod { get; set; }

    [Key]
    public int Id { get; set; }

    [Column("IdPedidoMProduto")]
    public int IdPedidoMproduto { get; set; }

    [StringLength(10)]
    public string RelacionadoOrdemCompra { get; set; }

    [ForeignKey("IdPedidoMproduto")]
    [InverseProperty("PedidoMaterial")]
    public virtual Produto IdPedidoMprodutoNavigation { get; set; }

    [InverseProperty("IdOrdemPedidoMaterialNavigation")]
    public virtual ICollection<OrdemCompra> OrdemCompra { get; set; } = new List<OrdemCompra>();
}