// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ERPSoft.DATA.Models;

public partial class PedidoServico
{
    [Required]
    [StringLength(250)]
    [Unicode(false)]
    public string Observacao { get; set; }

    [StringLength(150)]
    [Unicode(false)]
    public string Departamento { get; set; }

    [StringLength(150)]
    [Unicode(false)]
    public string Usuario { get; set; }

    [Column(TypeName = "date")]
    public DateTime DataCadastro { get; set; }

    [StringLength(150)]
    [Unicode(false)]
    public string NomeServico { get; set; }

    [StringLength(150)]
    [Unicode(false)]
    public string NomeFornecedor { get; set; }

    [StringLength(10)]
    public string DataFormatada { get; set; }

    public int Cod { get; set; }

    [Required]
    [StringLength(30)]
    [Unicode(false)]
    public string StatusServico { get; set; }

    [Key]
    public int Id { get; set; }

    [Column("IdPedidoSServico")]
    public int IdPedidoSservico { get; set; }

    [Column("IdPedidoSFornecedor")]
    public int IdPedidoSfornecedor { get; set; }

    [ForeignKey("IdPedidoSfornecedor")]
    [InverseProperty("PedidoServico")]
    public virtual Fornecedor IdPedidoSfornecedorNavigation { get; set; }

    [ForeignKey("IdPedidoSservico")]
    [InverseProperty("PedidoServico")]
    public virtual Servicos IdPedidoSservicoNavigation { get; set; }

    [InverseProperty("IdOrdemPedidoServicoNavigation")]
    public virtual ICollection<OrdemServico> OrdemServico { get; set; } = new List<OrdemServico>();
}