// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ERPSoft.DATA.Models;

public partial class Produto
{
    [Required]
    [StringLength(150)]
    public string Nome { get; set; }

    [Column("EAN")]
    public int Ean { get; set; }

    public int Preco { get; set; }

    public int? EstoqueMin { get; set; }

    public int? EstoqueIdeal { get; set; }

    public int? EstoqueAtual { get; set; }

    [Unicode(false)]
    public string Foto { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Unidade { get; set; }

    public int? PrecoTotal { get; set; }

    [Key]
    public int Id { get; set; }

    [InverseProperty("IdEntradaProdutoNavigation")]
    public virtual ICollection<Entrada> Entrada { get; set; } = new List<Entrada>();

    [InverseProperty("IdPedidoMprodutoNavigation")]
    public virtual ICollection<PedidoMaterial> PedidoMaterial { get; set; } = new List<PedidoMaterial>();

    [InverseProperty("IdSaidaProdutoNavigation")]
    public virtual ICollection<Saida> Saida { get; set; } = new List<Saida>();
}