// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ERPSoft.DATA.Models;

public partial class Saida
{
    public int EstoqueSaida { get; set; }

    [Column("EstoqueQTDE")]
    public int EstoqueQtde { get; set; }

    [StringLength(150)]
    [Unicode(false)]
    public string Usuario { get; set; }

    [StringLength(150)]
    [Unicode(false)]
    public string Departamento { get; set; }

    [Column(TypeName = "date")]
    public DateTime Data { get; set; }

    [StringLength(150)]
    [Unicode(false)]
    public string NomeProduto { get; set; }

    [StringLength(150)]
    [Unicode(false)]
    public string NomeFornecedor { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string DataFormatada { get; set; }

    [Key]
    public int Id { get; set; }

    public int IdSaidaProduto { get; set; }

    public int IdSaidaFornecedor { get; set; }

    [ForeignKey("IdSaidaFornecedor")]
    [InverseProperty("Saida")]
    public virtual Fornecedor IdSaidaFornecedorNavigation { get; set; }

    [ForeignKey("IdSaidaProduto")]
    [InverseProperty("Saida")]
    public virtual Produto IdSaidaProdutoNavigation { get; set; }
}