// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ERPSoft.DATA.Models;

public partial class Servicos
{
    [Required]
    [StringLength(150)]
    public string Nome { get; set; }

    [Required]
    public string Descricao { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Data { get; set; }

    [StringLength(150)]
    [Unicode(false)]
    public string NomeFornecedor { get; set; }

    [Key]
    public int Id { get; set; }

    public int IdFornecedor { get; set; }

    [ForeignKey("IdFornecedor")]
    [InverseProperty("Servicos")]
    public virtual Fornecedor IdFornecedorNavigation { get; set; }

    [InverseProperty("IdPedidoSservicoNavigation")]
    public virtual ICollection<PedidoServico> PedidoServico { get; set; } = new List<PedidoServico>();
}